name: Upload data to Google sheets
description: This action generates metrics for Figma library usage across Canonical Figma files

runs:
    using: "composite"
    steps:
        - name: Get latest metrics file
          id: get_latest_metrics
          run: |
              latest_folder=$(ls -td archive/*/ | head -1)
              latest_file="${latest_folder}figma-metrics.json"
              echo "latest_file=${latest_file}" >> $GITHUB_OUTPUT
          shell: bash

        - name: Transform data
          run: node transform.js $(ls -td archive/*/ | head -1)figma-metrics.json
          shell: bash

        - name: Read sheet1Data.json
          id: read_sheet1_data_json
          uses: jaywcjlove/github-action-read-file@main
          with:
              path: sheet1_data.json

        - name: Read sheet2Data.json
          id: read_sheet2_data_json
          uses: jaywcjlove/github-action-read-file@main
          with:
              path: sheet2_data.json

        - name: Read sheet3Data.json
          id: read_sheet3_data_json
          uses: jaywcjlove/github-action-read-file@main
          with:
              path: sheet3_data.json

        - name: Update worksheets
          id: update_worksheets
          uses: jroehl/gsheet.action@release
          with:
              spreadsheetId: 1vL8Z7BhmcLxkNGKQm6emI0gQwy_e4Lvq5PUqdCEw7C4
              commands: |
                  [
                  { "command": "getWorksheet", "args": { "worksheetTitle": "Source mix (custom vs components)" }},
                  { "command": "updateData", "args": { "data": ${{ steps.read_sheet1_data_json.outputs.content }} }},
                  { "command": "getWorksheet", "args": { "worksheetTitle": "Library mix" }},
                  { "command": "updateData", "args": { "data": ${{ steps.read_sheet2_data_json.outputs.content }} }},
                  { "command": "getWorksheet", "args": { "worksheetTitle": "Detached components" }},
                  { "command": "updateData", "args": { "data": ${{ steps.read_sheet3_data_json.outputs.content }} }}
