name: Upload data to Google sheets
description: This action generates metrics for Figma library usage across Canonical Figma files

runs:
    using: "composite"
    steps:
        - name: Get latest metrics file
          id: get_latest_metrics
          run: |
              latest_folder=$(ls -td archive/*/ | head -1)
              latest_file="${latest_folder}figma-metrics.json"
              echo "latest_file=${latest_file}" >> $GITHUB_OUTPUT
          shell: bash

        - name: Transform data
          run: node transform.js $(ls -td archive/*/ | head -1)figma-metrics.json
          shell: bash

        - name: Read sheet1_data.json
          id: read_sheet1_data
          uses: actions/github-script@v6
          with:
              script: |
                  const fs = require('fs')
                  const sheet1Data = JSON.parse(fs.readFileSync('sheet1_data.json', 'utf8'))
                  core.setOutput('sheet1_data', JSON.stringify(sheet1Data))

        - name: Read sheet2_data.json
          id: read_sheet2_data
          uses: actions/github-script@v6
          with:
              script: |
                  const fs = require('fs')
                  const sheet2Data = JSON.parse(fs.readFileSync('sheet2_data.json', 'utf8'))
                  core.setOutput('sheet2_data', JSON.stringify(sheet2Data))

        - name: Read sheet3_data.json
          id: read_sheet3_data
          uses: actions/github-script@v6
          with:
              script: |
                  const fs = require('fs')
                  const sheet3Data = JSON.parse(fs.readFileSync('sheet3_data.json', 'utf8'))
                  core.setOutput('sheet3_data', JSON.stringify(sheet3Data))

        - name: Update worksheets
          id: update_worksheets
          uses: jroehl/gsheet.action@release
          with:
              spreadsheetId: 1KC8k0460COgU9ZxBP9CRLEuunOjz4TlsQy4p82BNlA4
              commands: |
                  [
                      { "command": "getWorksheet", "args": { "worksheetTitle": "Source mix (custom vs components)" }},
                      { "command": "updateData", "args": { "data": ${{ steps.read_sheet1_data.outputs.sheet1_data }} }},
                      { "command": "getWorksheet", "args": { "worksheetTitle": "Library mix" }},
                      { "command": "updateData", "args": { "data": ${{ steps.read_sheet2_data.outputs.sheet2_data }} }},
                      { "command": "getWorksheet", "args": { "worksheetTitle": "Detached components" }},
                      { "command": "updateData", "args": { "data": ${{ steps.read_sheet3_data.outputs.sheet3_data }} }}
                  ]
