name: Generate Figma metrics
description: This action generates metrics for Figma library usage across Canonical Figma files

runs:
    using: "composite"
    steps:
        - name: Generate analytics
          run: node index.js
          shell: bash

        - name: Commit and push
          run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add archive/
              timestamp=$(date -u)
              git commit -m "${timestamp}" || exit 0
              git stash
              git pull --rebase
              git push
          shell: bash
