name: Figma Metrics and Google Sheets Update

on:
    #schedule:
    #    - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    generate_metrics_and_update_sheets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Generate Metrics
              uses: ./.github/actions/metrics

            - name: Upload to Google sheets
              uses: ./.github/actions/gsheets
