name: Figma Metrics and Google Sheets Update

on:
    #schedule:
    #    - cron: "0 0 * * 0"
    workflow_dispatch:

jobs:
    generate_metrics_and_update_sheets:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node 18
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Generate Metrics
              uses: ./.github/actions/metrics
              env:
                  FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
                  FIGMA_TEAM_ID: ${{ secrets.FIGMA_TEAM_ID }}
                  FIGMA_LIBRARY_FILES: ${{ secrets.FIGMA_LIBRARY_FILES }}

            - name: Upload to Google sheets
              uses: ./.github/actions/gsheets
              env:
                  GSHEET_CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
                  GSHEET_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
